modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="extrautilitiesrebirth"
version="1.7.3"
displayName="Extra Utilities Rebirth"
credits="Hi"
displayURL="https://www.curseforge.com/members/inzhefop/projects"
authors="inzhefop"
description='''
RELEASE
'''

[[dependencies.extrautilitiesrebirth]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



[[dependencies.extrautilitiesrebirth]]
    modId="allmods"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.extrautilitiesrebirth]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

